SELECT 
    ATC.COLUMN_ID as POS, 
    ATC.COLUMN_NAME as NAME, 
    ATC.DATA_TYPE as TYPE, 
    ATC.DATA_LENGTH as LEN, 
    NVL((SELECT 'Y' 
         FROM USER_CONS_COLUMNS UCC
         JOIN USER_CONSTRAINTS UC ON UCC.CONSTRAINT_NAME = UC.CONSTRAINT_NAME 
         WHERE UC.CONSTRAINT_TYPE = 'P' 
           AND UCC.TABLE_NAME = ATC.TABLE_NAME 
           AND UCC.COLUMN_NAME = ATC.COLUMN_NAME
    ), 'N') as PK, 
    ATC.NULLABLE, 
    ACC.COMMENTS as REMARK 
FROM USER_TAB_COLUMNS ATC
JOIN USER_COL_COMMENTS ACC ON ATC.TABLE_NAME = ACC.TABLE_NAME AND ATC.COLUMN_NAME = ACC.COLUMN_NAME 
WHERE ATC.TABLE_NAME = UPPER(?) 
ORDER BY ATC.COLUMN_ID
