SELECT ATC.COLUMN_ID as POS, ATC.COLUMN_NAME as NAME, ATC.DATA_TYPE as TYPE, ATC.DATA_LENGTH as LEN, 
(SELECT 'Y' FROM USER_CONS_COLUMNS UCC, USER_CONSTRAINTS UC WHERE UCC.CONSTRAINT_NAME = UC.CONSTRAINT_NAME AND UC.CONSTRAINT_TYPE = 'P' AND UCC.TABLE_NAME = ATC.TABLE_NAME AND UCC.COLUMN_NAME = ATC.COLUMN_NAME) as PK, 
ATC.NULLABLE, ACC.COMMENTS as REMARK 
FROM USER_TAB_COLUMNS ATC, USER_COL_COMMENTS ACC 
WHERE ATC.TABLE_NAME = ACC.TABLE_NAME 
AND ATC.COLUMN_NAME = ACC.COLUMN_NAME 
AND ATC.TABLE_NAME = ? 
ORDER BY ATC.COLUMN_ID
